version: '3.8'
services:
  node_app:
    image: node:16
    container_name: node-container
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start

