version: '3.8'
services:
  python_app:
    image: python:3.9
    container_name: python-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_ENV: development

